##########################################################################
# BLOCKCHAIN MMS EXPERIMENT - CONFIGTX - March/2021
# This profile detemines the mbblocknet configuration. It follows the 
# standard from other Fabric networks configuration.
# It contemplates an inter MB blockchain network consortium with 1DN and 2DN (so far). It also includes a solo orderer Org and the profile for
# a channel called NMIChannel. 
# Author: Wilson S. Melo Jr. - Inmetro
##########################################################################
---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &Orderer
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Orderer

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/orderer.mb/msp

        # turn off security for the channel
        AdminPrincipal: Role.MEMBER

    - &1DN
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: 1DN

        # ID to load the MSP definition as
        ID: 1DNMSP

        MSPDir: crypto-config/peerOrganizations/1dn.mb/msp

        # turn off security for the peer
        AdminPrincipal: Role.MEMBER

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.1dn.mb
              Port: 7051

    - &2DN
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: 2DN

        # ID to load the MSP definition as
        ID: 2DNMSP

        MSPDir: crypto-config/peerOrganizations/2dn.mb/msp

        # turn off security for the peer
        AdminPrincipal: Role.MEMBER

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.2dn.mb
              Port: 7051


################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: kafka

    Addresses:
        - orderer.mb:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 98 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        # Brokers:
        #     - 127.0.0.1:9092

    # EtcdRaft defines configuration which must be set when the "etcdraft"
    # orderertype is chosen.
    EtcdRaft:
        # The set of Raft replicas for this network. For the etcd/raft-based
        # implementation, we expect every replica to also be an OSN. Therefore,
        # a subset of the host:port items enumerated in this list should be
        # replicated under the Orderer.Addresses key above.
        Consenters:
            - Host: raft1.orderer.mb
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft1.orderer.mb/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft1.orderer.mb/tls/server.crt
            - Host: raft2.orderer.mb
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft2.orderer.mb/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft2.orderer.mb/tls/server.crt
            - Host: raft3.orderer.mb
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft3.orderer.mb/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft3.orderer.mb/tls/server.crt
    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    MBGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Orderer
        Consortiums:
            MBConsortium:
                Organizations:
                    - *1DN
                    - *2DN
    MBRaftGenesis:
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: raft1.orderer.mb
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft1.orderer.mb/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft1.orderer.mb/tls/server.crt
                - Host: raft2.orderer.mb
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft2.orderer.mb/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft2.orderer.mb/tls/server.crt
                - Host: raft3.orderer.mb
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft3.orderer.mb/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/orderer.mb/orderers/raft3.orderer.mb/tls/server.crt
            Addresses:
                - raft1.orderer.mb:7050
                - raft2.orderer.mb:7050
                - raft3.orderer.mb:7050	    
            Organizations:
                - *Orderer
        Consortiums:
            MBConsortium:
                Organizations:
                    - *1DN
                    - *2DN

    MBChannel:
        Consortium: MBConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *1DN
                - *2DN
