version: "2"

services:
  blk-client:
    container_name: blk-client
    image: prnascimento/blockchain-client-base:1.0.0
    build: .
    volumes:
      - ./:/usr/src/app
    cpus: 0.7
    mem_limit: 20M
    memswap_limit: 40M
